app/bookings/models.py
from datetime import date
from app import db




class Booking(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='SET NULL'))
    user_name = db.Column(db.String)
    tour_id = db.Column(db.Integer, db.ForeignKey('tour.id', ondelete='SET NULL'), nullable=False)
    tour_name=db.Column(db.String)
    people = db.Column(db.Integer)
    datecreated = db.Column(db.DateTime, default=date.today)


    def __init__(self,people=people, tour_name=None, user_id=None, user_name=user_name, tour_id=None):
        self.user_id = user_id
        self.user_name = user_name
        self.tour_id = tour_id
        self.tour_name=tour_name
        self.people= people

    def __repr__(self):
        return f'<Booking {self.tour_name}>'

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @staticmethod
    def get_by_user_id(user_id):
        return Booking.query.filter_by(user_id=user_id).all()
    
    @staticmethod
    def get_by_id(id):
        return Booking.query.get(id)

app/bookings/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField
from wtforms.validators import DataRequired


class BookingForm(FlaskForm):
    people = IntegerField('Numero de personas', validators=[DataRequired(), ])
    submit = SubmitField('Hacer Reserva')

app/bookings/__init__.py
from flask import Blueprint

bookings_bp= Blueprint('bookings', __name__, template_folder='templates')

from . import routes

app/bookings/routes.py
from flask import render_template, abort, redirect, url_for
from ..bookings.models import Booking
from . import bookings_bp
from werkzeug.exceptions import NotFound
from ..bookings.forms import BookingForm
from flask_login import  login_required, current_user

@bookings_bp.route("/bookings/<int:booking_id>", methods=['GET', 'POST'])
@login_required
def show_booking(booking_id):
        booking = Booking.get_by_id(booking_id)
        if booking is None:
            raise NotFound(booking_id)
        
        return render_template("booking_view.html", booking=booking)

@bookings_bp.route("/bookings/delete/<int:booking_id>/", methods=['POST', ])
@login_required
def delete_booking(booking_id):
   
    booking = Booking.get_by_id(booking_id)
    if booking is None:
        abort(404)
    booking.delete()
    return redirect(url_for('tour.index'))

@bookings_bp.route("/bookings")
@login_required
def show_bookings():
    user_id = current_user.id
    bookings = Booking.get_by_user_id(user_id)
    return render_template("booking_list.html", bookings=bookings)

app/bookings/templates/booking_list.html
{% extends "base_template.html" %}

{% block title %}{{ user_name }}{% endblock %}
{% block content %}
Reservas:
<div id="bookings">
    {% if bookings %}
        {% for booking in bookings %}
        <a href="{{ url_for('bookings.show_booking', booking_id=booking.id) }}">{{ booking.tour_name}}</a>
        {% endfor %}
    {% else %}
    <p>No tiene reservas disponibles.</p>
{% endif %}
</div>
{%endblock%}

app/bookings/templates/booking_view.html
{% extends "base_template.html" %}

{% block title %}{{ booking.user_name }}{% endblock %}

{% block content %}
    <h1>Reserva</h1>
    <li>Tour reservado: {{booking.tour_name}}
    <li>Fecha de reserva:{{ booking.datecreated.strftime('%d-%m-%Y')}}
    <li>Cantidad de personas:{{booking.people}}
        <form action="{{ url_for('bookings.delete_booking', booking_id=booking.id) }}" method="post" novalidate>
            <input type="submit" value="Cancelar Reserva" />
        </form>
{% endblock%}